### PR TITLE
Compile the book in buildbot.

### PR DESCRIPTION
**Pull request by vext01**
Compile the book in buildbot.

### CODE REVIEW

**Comment by vext01** [comment]
bors ping

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
bors try-

**Comment by vext01** [comment]
bors try

**Comment by vext01** [comment]
(Sorry about all of the bors fiddling above -- should work now, needs squashing).

**Comment by ltratt** [comment]
Please squash.

**Comment by vext01** [comment]
Splat. Updated PR title and text.

**Pull request merged**
